name: $(Date:yyyyMMdd).$(Rev:.r)
trigger: none
pr: none
steps:
  - template: templates/npm-setup.yml

  - script: npm run build:storybook
    displayName: Build Storybook

  - template: templates/publish-artifacts.yml
    parameters:
      appToPublish: 'design-system'
