name: $(Date:yyyyMMdd).$(Rev:.r)
trigger:
  - master
pr: none
jobs:
  - job: PrepareAppRelease
    steps:
      - script: mkdir $(System.ArtifactsDirectory)/monorepopackage
        displayName: CreateDownloadOutputDirectory

      - task: DownloadBuildArtifacts@0
        displayName: 'Download Build Artifacts'
        inputs:
          buildType: specific
          project: 'f6995a74-0552-4d3b-b372-a80af3d9b89a'
          pipeline: 4
          downloadType: single
          artifactName: drop
          downloadPath: '$(System.ArtifactsDirectory)/monorepopackage'

      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: '$(System.ArtifactsDirectory)/monorepopackage/*.zip'
          destinationFolder: $(System.DefaultWorkingDirectory)/dist
          cleanDestinationFolder: true

      - task: PowerShell@2
        displayName: Read and tag affected apps in artifact
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          GITHUB_TOKEN: $(GithubToken)
        inputs:
          targetType: 'filePath'
          filePath: 'tools/pipelines/scripts/read-and-tag-affected-apps-in-artifact.ps1'
          pwsh: true

      - template: templates/publish-artifacts.yml
