name: $(Date:yyyyMMdd).$(Rev:.r)
trigger: none
pool:
  vmImage: ubuntu-latest

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

stages:
  - stage: BuildAndTestAffected
    jobs:
      - job: BuildAffected
        steps:
          - template: templates/npm-setup.yml

          - task: PowerShell@2
            displayName: Build Affected
            inputs:
              targetType: 'filePath'
              filePath: 'tools/pipelines/scripts/build-affected.ps1'
              pwsh: true

          - task: PowerShell@2
            displayName: Create affected-apps.txt
            inputs:
              targetType: 'filePath'
              filePath: 'tools/pipelines/scripts/create-affected-apps-txt.ps1'
              pwsh: true

          - template: templates/publish-artifacts.yml

      - job: TestAffected
        steps:
          - template: templates/npm-setup.yml

          - script: npm run affected:test -- --base=origin/master --head=HEAD
            displayName: Test Affected

          - script: npm run codecov -- $(CodeCovToken) --disable=gcov
            displayName: Send to Codecov

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/*.xml'
              searchFolder: '$(System.DefaultWorkingDirectory)/junit'
              mergeTestResults: true
              failTaskOnFailedTests: true
              publishRunAttachments: true

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/**/*xml'
              failIfCoverageEmpty: false

      - job: PrepareForOtherPipelines
        steps:
          - template: templates/npm-setup.yml

          - task: PowerShell@2
            displayName: Tags for Affected Apps
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            inputs:
              targetType: 'filePath'
              filePath: 'tools/pipelines/scripts/tags-for-affected-apps.ps1'
              pwsh: true
