trigger:
  - master
pr:
  - master

variables:
  CI: 'true'
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestId) # You can use $(System.PullRequest.PullRequestNumber if your pipeline is triggered by a PR from GitHub ONLY)
    TARGET_BRANCH: $[replace(variables['System.PullRequest.TargetBranch'],'refs/heads/','origin/')]
    BASE_SHA: $(git merge-base $(TARGET_BRANCH) HEAD)
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(Build.SourceBranchName)
    BASE_SHA: $(git rev-parse HEAD~1)
  HEAD_SHA: $(git rev-parse HEAD)
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

jobs:
  - job: master
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # Set Azure Devops CLI default settings
      - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
        displayName: 'Set default Azure DevOps organization and project'

      # Get last successfull commit from Azure Devops CLI
      - bash: |
          LAST_SHA=$(az pipelines build list --branch $(Build.SourceBranchName) --definition-ids $(System.DefinitionId) --result succeeded --top 1 --query "[0].triggerInfo.\"ci.sourceSha\"")
          if [ -z "$LAST_SHA" ]
          then
            echo "Last successful commit not found. Using fallback 'HEAD~1': $BASE_SHA"
          else
            echo "Last successful commit SHA: $LAST_SHA"
            echo "##vso[task.setvariable variable=BASE_SHA]$LAST_SHA"
          fi
        displayName: 'Get last successful commit SHA'
        condition: ne(variables['Build.Reason'], 'PullRequest')
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

      # Required for nx affected if we're on a branch
      - script: git branch --track master origin/master

      - task: Cache@2
        inputs:
          key: '"yarn" | "$(Agent.OS)" | yarn.lock'
          restoreKeys: |
            "yarn" | "$(Agent.OS)"
            "yarn"
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages

      - script: yarn --frozen-lockfile
        displayName: 'Install dependencies'

      - script: npx nx format:check --base=$(BASE_SHA)
        displayName: 'Format check'
      - script: npx nx affected --base=$(BASE_SHA) -t lint --parallel=3
        displayName: 'Lint'
      - script: npx nx affected --base=$(BASE_SHA) -t test --parallel=3
        displayName: 'Test'
      - script: npx nx affected --base=$(BASE_SHA) -t build --parallel=3
        displayName: 'Build'

      # archive and publish artifacts
      - task: ArchiveFiles@2
        displayName: Archive Build Artifacts
        condition: always()
        continueOnError: true
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: $(Build.ArtifactStagingDirectory)/build/$(Build.BuildId).zip
      - task: PublishBuildArtifacts@1
        displayName: Publish Build Artifacts
        condition: always()
        continueOnError: true
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)/build/$(Build.BuildId).zip
          artifactName: 'drop'

      # Tag build to trigger release pipelines
      - script: |
          projects=`npx nx show projects --affected --base=$(BASE_SHA) --head=$(HEAD_SHA)`
          echo "Touched projects:"
          echo $projects

          for project in ${projects//,/ }
          do
            echo "##vso[build.addbuildtag]$project"
            echo "Creating tag for: $project"
          done
        displayName: 'Tag build'
